{
 "title": "Minecraft Server Monitoring Service",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": { "query": "label_values(server)" } }
  ]
 },
 "panels": [
  {
   "title": "User Namen \"${server}\"",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "minecraft_players{instance=~\"zeus:8080|nyx:8088\", server=\"${server}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Minecraft Version",
   "type": "stat",
   "description": "Minecraft Version",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Minecraft Server \"${server}\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "minecraft_users_online{instance=~\"zeus:8080|nyx:8088\", server=\"${server}\"}",
     "legendFormat": "Online Users"
    },
    {
     "expr": "minecraft_users_max{instance=\"zeus:8080\", server=\"Foxtrott Minecraft Server\"}",
     "legendFormat": "Max Users"
    }
   ]
  },
  {
   "title": "User Namen \"${server}\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "minecraft_players{instance=~\"zeus:8080|nyx:8088\", server=\"${server}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "MCSMONS Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Measurement Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "expr": "minecraft_mcs_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Measurement Per-Second Average Rate [1h]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "rate(minecraft_mcs_count[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MCSMONS Version",
   "type": "stat",
   "description": "Minecraft Service Version",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_mcs_count", "legendFormat": "__auto" }
   ]
  }
 ]
}