name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version environment variable
        run: echo "VERSION=$(git describe --always --tags)" >> $GITHUB_ENV

      - name: Build Docker image using Makefile
        run: make image

      - name: Retag image for GitHub Container Registry
        run: |
          docker tag mcsmons:${{ env.VERSION }} ghcr.io/${{ github.repository_owner }}/mcsmons:${{ env.VERSION }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/mcsmons:${{ env.VERSION }}
